apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    app: myimage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myimage
  template:
    metadata:
      labels:
        app: myimage
    spec:
      containers:
      - name: mycontainer
        image: devops01docker/test1
        ports:
        - containerPort: 80
