          apiVersion: v1
          kind: Service 
          metadata:
            name: myservice
            labels:
              app: frontend
          spec:
            selector:
              app: frontend
            type: NodePort
              ports:
              - nodePort: 30008
                port: 80
                targetPort: 80
